# Generated by Django 3.2.12 on 2022-12-05 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=250)),
                ('videolink', models.CharField(max_length=100)),
                ('banner_image', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=300)),
                ('hotel_rating_standard', models.CharField(max_length=300)),
                ('seo_search_engine', models.BooleanField()),
                ('seo_meta_title', models.CharField(max_length=50)),
                ('seo_meta_tag', models.CharField(max_length=50)),
                ('seo_desc', models.TextField(max_length=250)),
                ('availability', models.BooleanField()),
                ('havana_lobby', models.BooleanField()),
                ('fiesta_rest', models.BooleanField()),
                ('hotel_transport', models.BooleanField()),
                ('free_luggage', models.BooleanField()),
                ('loundry', models.BooleanField()),
                ('pets', models.BooleanField()),
                ('ticket', models.BooleanField()),
                ('car_hire', models.BooleanField()),
                ('bicycle_hire', models.BooleanField()),
                ('flat_tv', models.BooleanField()),
                ('internet_wifi', models.BooleanField()),
                ('coffee_tea', models.BooleanField()),
                ('loundry_dry', models.BooleanField()),
                ('motels', models.BooleanField()),
                ('resorts', models.BooleanField()),
                ('lodges', models.BooleanField()),
                ('swimming_pool', models.BooleanField()),
                ('feature_image', models.CharField(max_length=300)),
                ('publish', models.CharField(choices=[('publish', 'Publish'), ('draft', 'Draft')], default='publish', max_length=10)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.country')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.state')),
                ('user_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.user')),
            ],
        ),
        migrations.CreateModel(
            name='NewRoomAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HotelPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=20)),
                ('current_price', models.CharField(max_length=300)),
                ('previous_price', models.CharField(max_length=300)),
                ('discount', models.CharField(max_length=300)),
                ('hotel_price_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='HotelPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', models.CharField(max_length=300)),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
            ],
        ),
    ]
