# Generated by Django 3.2.12 on 2022-12-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='banner_image',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='seo_meta_tag',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='seo_meta_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='videolink',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='hotelprice',
            name='hotel_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='newroomattribute',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
