# Generated by Django 3.2.12 on 2022-12-05 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_name', models.CharField(max_length=50)),
                ('lang_direction', models.CharField(choices=[('left_to_right', 'Left to Right'), ('right_to_left', 'Right to Left')], default='left_to_right', max_length=30)),
                ('lang_key', models.CharField(max_length=20)),
                ('lang_value', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BlogCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('thumbnail', models.CharField(max_length=50)),
                ('tags', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=50)),
                ('allow_blog_seo', models.CharField(max_length=50)),
                ('meta_tag', models.CharField(max_length=50)),
                ('meta_desc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sign', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp', models.BooleanField()),
                ('smtp_host', models.CharField(max_length=20)),
                ('smtp_port', models.TextField(max_length=7)),
                ('smtp_username', models.CharField(max_length=20)),
                ('smtp_password', models.CharField(max_length=20)),
                ('from_email', models.CharField(max_length=20)),
                ('from_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(max_length=20)),
                ('email_subject', models.CharField(max_length=20)),
                ('email_body', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FAQPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_logo', models.CharField(max_length=30)),
                ('footer_logo', models.CharField(max_length=20)),
                ('favicon', models.CharField(max_length=30)),
                ('breadcumb_banner', models.CharField(max_length=30)),
                ('website_title', models.CharField(max_length=20)),
                ('theme_color', models.CharField(max_length=15)),
                ('secondary_color', models.CharField(max_length=15)),
                ('sign_up_verification', models.BooleanField()),
                ('disqus', models.BooleanField()),
                ('disqus_website_name', models.CharField(max_length=25)),
                ('footer_text', models.TextField(max_length=100)),
                ('copyright_text', models.TextField(max_length=100)),
                ('error_img', models.CharField(max_length=20)),
                ('error_title', models.TextField(max_length=100)),
                ('error_text', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=30)),
                ('img', models.CharField(max_length=50)),
                ('message', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NewPagefaq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=50)),
                ('allow_seo_page', models.CharField(max_length=50)),
                ('meta_tag', models.CharField(max_length=50)),
                ('meta_desc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('blog_section', models.CharField(max_length=50)),
                ('space_section', models.CharField(max_length=50)),
                ('home_page_settings', models.CharField(max_length=50)),
                ('email_settings', models.CharField(max_length=50)),
                ('lang_section', models.CharField(max_length=50)),
                ('user_manage_section', models.CharField(max_length=50)),
                ('hotel_section', models.CharField(max_length=50)),
                ('car_section', models.CharField(max_length=50)),
                ('payment_settings', models.CharField(max_length=50)),
                ('social_settings', models.CharField(max_length=50)),
                ('seo_tools', models.CharField(max_length=50)),
                ('manage_role_section', models.CharField(max_length=50)),
                ('tour_section', models.CharField(max_length=50)),
                ('general_settings_section', models.CharField(max_length=50)),
                ('menu_page_section', models.CharField(max_length=50)),
                ('location_section', models.CharField(max_length=50)),
                ('manage_staff_section', models.CharField(max_length=50)),
                ('subscriber_section', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=30)),
                ('img', models.CharField(max_length=50)),
                ('button_name', models.CharField(max_length=20)),
                ('button_link', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('content', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_name', models.CharField(max_length=50)),
                ('lang_direction', models.CharField(choices=[('left_to_right', 'Left to Right'), ('right_to_left', 'Right to Left')], default='left_to_right', max_length=30)),
                ('lang_key', models.CharField(max_length=20)),
                ('lang_value', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=100)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.country')),
            ],
        ),
        migrations.CreateModel(
            name='MemberBackgroud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=50)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.member')),
            ],
        ),
    ]
