# Generated by Django 3.2.12 on 2022-12-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='blog_section',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='role',
            name='car_section',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='role',
            name='email_settings',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='role',
            name='general_settings_section',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='role',
            name='home_page_settings',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='role',
            name='hotel_section',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='role',
            name='lang_section',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='role',
            name='location_section',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='role',
            name='manage_role_section',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='role',
            name='manage_staff_section',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='role',
            name='menu_page_section',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='role',
            name='payment_settings',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='role',
            name='seo_tools',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='role',
            name='social_settings',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='role',
            name='space_section',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='role',
            name='subscriber_section',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='role',
            name='tour_section',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='role',
            name='user_manage_section',
            field=models.BooleanField(),
        ),
    ]
