from django.contrib import admin
from .models import *
# Register your models here.

admin.site.register(User)
admin.site.register(Country)
admin.site.register(State)
admin.site.register(Category)
admin.site.register(Role)
admin.site.register(Staff)
admin.site.register(AdminLanguage)
admin.site.register(WebsiteLanguage)
admin.site.register(Slider)
admin.site.register(Member)
admin.site.register(MemberBackgroud)
admin.site.register(EmailTemplate)
admin.site.register(EmailConfiguration)
admin.site.register(GeneralSetting)
admin.site.register(PaymentGateway)
admin.site.register(Currency)
admin.site.register(WithdrawMethod)
admin.site.register(FAQPage)
admin.site.register(NewPagefaq)
admin.site.register(BlogCat)
admin.site.register(BlogPost)
admin.site.register(Attendance)
admin.site.register(IP_Address)