from django.urls import path
from django.views.decorators.cache import cache_page
from .views import *

urlpatterns = [
    path("user/",ListUserGeneric.as_view()),
    path("user/<int:pk>/",cache_page(60*1)(UserGeneric.as_view())),
    path("country/",ListCountryGeneric.as_view()),
    path("country/<int:pk>/",cache_page(60*1)(CountryGeneric.as_view())),
    path("state/",ListStateGeneric.as_view()),
    path("state/<int:pk>/",cache_page(60*1)(StateGeneric.as_view())),
    path("category/",ListCategoryGeneric.as_view()),
    path("category/<int:pk>/",cache_page(60*1)(CategoryGeneric.as_view())),
    path("role/",ListRoleGeneric.as_view()),
    path("role/<int:pk>/",cache_page(60*1)(RoleGeneric.as_view())),
    path("staff/",ListStaffGeneric.as_view()),
    path("staff/<int:pk>/",cache_page(60*1)(StaffGeneric.as_view())),
    path("adminlang/",ListAdminLanguageGeneric.as_view()),
    path("adminlang/<int:pk>/",cache_page(60*1)(AdminLanguageGeneric.as_view())),
    path("websitelang/",ListWebsiteLanguageGeneric.as_view()),
    path("websitelang/<int:pk>/",cache_page(60*1)(WebsiteLanguageGeneric.as_view())),
    path("slider/",ListSliderGeneric.as_view()),
    path("slider/<int:pk>/",cache_page(60*1)(SliderGeneric.as_view())),
    path("member/",ListMemberGeneric.as_view()),
    path("member/<int:pk>/",cache_page(60*1)(MemberGeneric.as_view())),
    path("memberbg/",ListMemberBackgroundGeneric.as_view()),
    path("memberbg/<int:pk>/",cache_page(60*1)(MemberBackgroundGeneric.as_view())),
    path("emailtemp/",ListEmailTemplateGeneric.as_view()),
    path("emailtemp/<int:pk>/",cache_page(60*1)(EmailTemplateGeneric.as_view())),
    path("emailconfig/",ListEmailConfigurationGeneric.as_view()),
    path("emailconfig/<int:pk>/",cache_page(60*1)(EmailConfigurationGeneric.as_view())),
    path("generalsetting/",ListGeneralSettingGeneric.as_view()),
    path("generalsetting/<int:pk>/",cache_page(60*1)(GeneralSettingGeneric.as_view())),
    path("paymentgateway/",ListPaymentGatewayGeneric.as_view()),
    path("paymentgateway/<int:pk>/",cache_page(60*1)(PaymentGatewayGeneric.as_view())),
    path("currency/",ListCurrencyGeneric.as_view()),
    path("currency/<int:pk>/",cache_page(60*1)(CurrencyGeneric.as_view())),
    path("withdrawmethod/",ListWithdrawMethodGeneric.as_view()),
    path("withdrawmethod/<int:pk>/",cache_page(60*1)(WithdrawMethodGeneric.as_view())),
    path("faqpage/",ListFAQPageGeneric.as_view()),
    path("faqpage/<int:pk>/",cache_page(60*1)(FAQPageGeneric.as_view())),
    path("newpagefaq/",ListNewPagefaqGeneric.as_view()),
    path("newpagefaq/<int:pk>/",cache_page(60*1)(NewPagefaqGeneric.as_view())),
    path("blogcat/",ListBlogCatGeneric.as_view()),
    path("blogcat/<int:pk>/",cache_page(60*1)(BlogCatGeneric.as_view())),
    path("blogpost/",ListBlogPostGeneric.as_view()),
    path("blogpost/<int:pk>/",cache_page(60*1)(BlogPostGeneric.as_view())),
    path("ip/", index),
    path("logo/",ListLogoGeneric.as_view()),
    path("logo/<int:pk>/",cache_page(60*1)(LogoGeneric.as_view())),
    path("landingpage/",ListLandingPageGeneric.as_view()),
    path("landingpage/<int:pk>/",cache_page(60*1)(LandingPageGeneric.as_view())),
    path("sectionactivity/",ListSectionActivityGeneric.as_view()),
    path("sectionactivity/<int:pk>/",cache_page(60*1)(SectionActivityGeneric.as_view())),
    path("sectiontour/",ListSectionTourGeneric.as_view()),
    path("sectiontour/<int:pk>/",cache_page(60*1)(SectionTourGeneric.as_view())),
    path("sectionhotel/",ListSectionHotelGeneric.as_view()),
    path("sectionhotel/<int:pk>/",cache_page(60*1)(SectionHotelGeneric.as_view())),
    path("sectionfeature/",ListSectionFeatureGeneric.as_view()),
    path("sectionfeature/<int:pk>/",cache_page(60*1)(SectionFeatureGeneric.as_view())),
    path("blog/",ListBlogGeneric.as_view()),
    path("blog/<int:pk>/",cache_page(60*1)(BlogGeneric.as_view())),
    path("nearbydest/",ListNearbyDestinationGeneric.as_view()),
    path("nearbydest/<int:pk>/",cache_page(60*1)(NearbyDestinationGeneric.as_view())),
    path("footer/",ListFooterGeneric.as_view()),
    path("footer/<int:pk>/",cache_page(60*1)(FooterGeneric.as_view())),
    path("helpline/",ListHelplineGeneric.as_view()),
    path("helpline/<int:pk>/",cache_page(60*1)(HelplineGeneric.as_view())),
    path("banner/",ListBannerGeneric.as_view()),
    path("banner/<int:pk>/",cache_page(60*1)(BannerGeneric.as_view())),
    path('', home, name='home'),
    path('success' , success , name='success')

]