# Generated by Django 3.2.12 on 2022-12-05 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=250)),
                ('youtube_link', models.CharField(max_length=50)),
                ('duration', models.IntegerField()),
                ('min_people', models.CharField(max_length=50)),
                ('max_people', models.CharField(max_length=50)),
                ('banner_image', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('current_price', models.IntegerField()),
                ('previous_price', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('seo_seach_engine', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=5)),
                ('seo_meta_title', models.CharField(max_length=50)),
                ('seo_meta_tag', models.CharField(max_length=50)),
                ('seo_desc', models.TextField(max_length=250)),
                ('availability', models.BooleanField()),
                ('wifi', models.BooleanField()),
                ('gym', models.BooleanField()),
                ('mountain_bike', models.BooleanField()),
                ('sat_office', models.BooleanField()),
                ('staff_lounge', models.BooleanField()),
                ('golf_cages', models.BooleanField()),
                ('aerobics', models.BooleanField()),
                ('cultural', models.BooleanField()),
                ('nature_adventure', models.BooleanField()),
                ('marine', models.BooleanField()),
                ('independent', models.BooleanField()),
                ('activities', models.BooleanField()),
                ('festival_events', models.BooleanField()),
                ('special_interests', models.BooleanField()),
                ('feature_image', models.CharField(max_length=50)),
                ('publish', models.CharField(choices=[('publish', 'Publish'), ('draft', 'Draft')], default='publish', max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.category')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.country')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.state')),
                ('user_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.user')),
            ],
        ),
        migrations.CreateModel(
            name='ExeAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ExeCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FAQS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=50)),
                ('exe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.exe')),
            ],
        ),
        migrations.CreateModel(
            name='ExePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exe_name', models.CharField(max_length=20)),
                ('current_price', models.CharField(max_length=300)),
                ('previous_price', models.CharField(max_length=300)),
                ('discount', models.CharField(max_length=300)),
                ('person_type', models.CharField(max_length=300)),
                ('min_age', models.IntegerField()),
                ('max_age', models.IntegerField()),
                ('person_price', models.IntegerField()),
                ('extra_price_name', models.CharField(max_length=20)),
                ('extra_price', models.IntegerField()),
                ('freq', models.CharField(choices=[('one_time', 'One Time'), ('per_day', 'Per Day')], default='one_time', max_length=10)),
                ('exe_price_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.exe')),
            ],
        ),
        migrations.CreateModel(
            name='Exe_Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=250)),
                ('exe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.exe')),
            ],
        ),
        migrations.CreateModel(
            name='Exe_Include',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('exe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.exe')),
            ],
        ),
        migrations.CreateModel(
            name='Exe_Exclude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('exe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.exe')),
            ],
        ),
    ]
