# Generated by Django 3.2.12 on 2022-12-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exe',
            name='address',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='exe',
            name='banner_image',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='exe',
            name='feature_image',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='exe',
            name='seo_meta_tag',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exe',
            name='seo_meta_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exe',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exe',
            name='youtube_link',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='exe_exclude',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exe_include',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exe_itinerary',
            name='content',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='exe_itinerary',
            name='desc',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='exe_itinerary',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='execat',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='execat',
            name='slug',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exeprice',
            name='exe_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='faqs',
            name='content',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='faqs',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
